---
title: "Earth Mover's Distance"
author: Danny McClanahan, Allie Greenplate, and Sierra Barone
editor: Sierra Barone
output: html_document
---


```{r set paths}
knitr::opts_chunk$set(echo = TRUE)

# install packages that are not in R by default, including flowCore and CytoTools
# install.packages('devtools')
# if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("flowCore")
#CytoTools_path = paste(EMD_root_path, "CytoTools R Package", sep="")
# devtools::install_local(CytoTools_path)

##  Set the root path to the folder with this file
EMD_root_path = "C:/Users/Sierra/Box/Work From Home/R Code/Prepared EMD Code and Files/Files for EMD/"
EMD_files_path = EMD_root_path
final_heatmap_pdf = paste(EMD_root_path, "heatmap_emd.pdf", sep="")

# load libraries
library(devtools)
library(CytoTools)
library(gplots)
library(flowCore)
```

## Configure

This is where the heatmap color palette is chosen as well as the file output names. 

```{r configure}
## Color palette for heatmap and file output names
color_palette <- colorRampPalette(
    c("#24658C", "#5CBAA7", "#9ED2A4", "#E2E998", "#FBF7BF", "#FDDC86",
      "#F8A05A", "#EF6342", "#D43E4F")
)(n = 50)
emd_tsne_means_outfile <- "emd_tsne_means.csv"
emd_tsne_variances_outfile <- "emd_tsne_variances.csv"
emd_tsne_medians_outfile <- "emd_tsne_medians.csv"
emd_heatmap_outfile <- "heatmap_emd.pdf"
emd_heatmap_outfile_hier <- "hierarchical_heatmap_emd.pdf"
```

## Sort

Here, the FCS files are sorted in the order you would like for them to be listed and to appear in the heatmap.

```{r sort files}
# Sort the files in the order in which you would like them to appear in the heatmap
sorted_cytof_data <- CytoTools::read_files_sorted(
    path = EMD_files_path,
    extensions = c("fcs"),split_by = c("_"," "))

day <- vector()
for (i in 1:length(sorted_cytof_data)){
  day[i] <- as.numeric(sub("Day ", "",strsplit(names(sorted_cytof_data)[[i]],"_")[[1]][13]))}
order = order(day)  
updated_sorted_data <-list()
for (s in 1:length(order)){
updated_sorted_data[[s]]<-sorted_cytof_data[[order[s]]]
names(updated_sorted_data)[[s]]<-names(sorted_cytof_data)[[order[s]]]}
```

## EMD Analysis

This is where the EMD analysis is performed on the t-SNE axes and a PDF is generated. 

```{r EMD analysis on t-SNE, message=FALSE, warning=FALSE}

### EMD analysis on t-SNE axes
tsne_matrices <- lapply(updated_sorted_data, function (fcs_df) {
    as.matrix(fcs_df[,c("tSNE1", "tSNE2")])
})

## This part runs EMD and takes a minute or two
emd_pairwise_analysis <- CytoTools::pairwise_emd(
    tsne_matrices, downsample_rows = 200L, comparison_runs = 10L,
    summary_funs = list(
        mean = mean,
        variance = var,
        median = median),
    verbose_timing = FALSE)

## save the EMD summary stats matrices to file
## note: read these back in with read.csv(filename, check.names = FALSE) to keep dimnames
write.csv(emd_pairwise_analysis$mean, paste(EMD_root_path, emd_tsne_means_outfile,sep = ""))
write.csv(emd_pairwise_analysis$variance, paste(EMD_root_path, emd_tsne_variances_outfile,sep = ""))
write.csv(emd_pairwise_analysis$median, paste(EMD_root_path, emd_tsne_medians_outfile,sep = ""))

# A heatmap of EMD stats will be exported to a PDF file within your current working directory
pdf(paste(EMD_root_path, emd_heatmap_outfile, sep =""))
plot_det = CytoTools::plot_pairwise_comparison(
    emd_pairwise_analysis$mean,
    pcnt_similarity_scale = TRUE,
    ## play with the number of colors in this variable (at the top of this file n = #)
    ## if the coloration seems weird or the color key is blank
    col = color_palette)
print(plot_det)
dev.off()

# A hierarchically clustered heatmap of EMD stats will be exported to a PDF file within your current working directory
pdf(paste(EMD_root_path, emd_heatmap_outfile_hier, sep =""))
hier_plot_det = CytoTools::plot_pairwise_comparison(
    emd_pairwise_analysis$mean,
    with_dendrograms = T,
    pcnt_similarity_scale = TRUE,
    ## play with the number of colors in this variable (at the top of this file n = #)
    ## if the coloration seems weird or the color key is blank
    col = color_palette)
print(hier_plot_det)
dev.off()

## save the hierarchically clustered EMD summary stats matrices to file
hier_emd_pairwise_analysis = emd_pairwise_analysis
hier_emd_pairwise_analysis$mean = emd_pairwise_analysis$mean[c(rev(hier_plot_det$rowInd)),c(hier_plot_det$colInd)]
hier_emd_pairwise_analysis$median = emd_pairwise_analysis$median[c(rev(hier_plot_det$rowInd)),c(hier_plot_det$colInd)]
hier_emd_pairwise_analysis$variance = emd_pairwise_analysis$variance[c(rev(hier_plot_det$rowInd)),c(hier_plot_det$colInd)]
write.csv(hier_emd_pairwise_analysis$mean, paste(EMD_root_path, "hier_",emd_tsne_means_outfile,sep = ""))
write.csv(hier_emd_pairwise_analysis$variance, paste(EMD_root_path, "hier_",emd_tsne_variances_outfile,sep = ""))
write.csv(hier_emd_pairwise_analysis$median, paste(EMD_root_path, "hier_",emd_tsne_medians_outfile,sep = ""))
```






