---
title: "Data Analysis Workflow Using Fold Change RAPID Todd's Data"
author: "Sierra Barone"
date: "10/09/2020"
output: pdf_document
editor_options: 
  chunk_output_type: inline
---

## Fold Change Risk Assessment Population IDentification (RAPID) Workflow

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# uncomment lines below to install packages
# install.packages("survminer", repos = "http://cran.us.r-project.org")
# install.packages("Rtsne", repos = "http://cran.us.r-project.org")
# install.packages("devtools", repos = "http://cran.us.r-project.org")
# devtools::install_github("cytolab/mem")
# install.packages("tidyverse", repos = "http://cran.us.r-project.org")
# if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
# BiocManager::install("flowCore")
# BiocManager::install("FlowSOM")
# BiocManager::install("Biobase")
# install.packages("ggpubr", repos = "http://cran.us.r-project.org")
# install.packages(paste(getwd(), sep=""), type = "source", repos=NULL)

# load packages into the working library
library(devtools)
library(MEM)
library(RAPID)
library(tidyverse)
library(ggpubr)
library(flowCore)
library(Biobase)
library(FlowSOM)
library(survival)
library(survminer)
library(plyr)
library(Rtsne)

# set working directory 
setwd(paste(getwd(),"/data_files/all_stim_dataset/", sep = ""))

# read in csv file
csv.file <- dir(pattern = "*fc.csv")
fold.change.data = read.csv(csv.file)

os.file <- dir(pattern = "*survival.csv")
os.data= read.csv(os.file)

# rename levels for stim condition
levels(fold.change.data$stim_condition)<-c("H2O2","IFNa","IL-2","IL-6")
levels(fold.change.data$phospho)<-c(unique(fold.change.data$phospho))
fold.change.data$fold_change[is.na(fold.change.data$fold_change)] <- 0
```

```{r find clinically significant clusters}
dir.create(file.path(getwd(), "output files"), showWarnings = FALSE)

for (z in 1:length(levels(fold.change.data$stim_condition))){
  for (y in 1:length(levels(fold.change.data$phospho))){
  fold.change <- fold.change.data %>%
    dplyr::filter(`stim_condition` == levels(fold.change.data$stim_condition)[z],`phospho`== levels(fold.change.data$phospho)[y])

split.by.cluster = split(fold.change,fold.change$FlowSOM_cluster_ID)

IQR <- list()
for (s in 1: length(split.by.cluster)){
  IQR[[s]] = IQR(split.by.cluster[[s]]$fold_change)}
all.IQRs = do.call(rbind,IQR) 


split.groups <- list()
for (e in 1:length(split.by.cluster)){
  split.groups[[e]] <-(split.by.cluster[[e]]$fold_change>all.IQRs[[e]])
    split.groups[[e]][split.groups[[e]]==TRUE] = 1
    }
  cluster.groups= do.call(rbind,split.groups)
  colnames(cluster.groups)<-c(split.by.cluster[["1"]][["patient_ID"]])

  survival_plot <- list()

  for (r in 1:nrow(cluster.groups)){
    Group <- factor(cluster.groups[r,], levels = c(0,1), labels = c("Low", "High"))
    survival_data1 = cbind(os.data,Group)
    model1 <- survfit(Surv(PFS.Time, PFS.Status) ~ Group, data=survival_data1)
    model2 <- coxph(Surv(PFS.Time, PFS.Status) ~ Group, data=survival_data1)
    cox.summary = summary(model2)
    survival_stat = cox.summary$coefficients
    CI = cox.summary$conf.int
     
    
    if (summary(Group)[1]<=2){
    survival_stat[,5] <- 1}
    if (summary(Group)[2]<=2){
      survival_stat[,5] <- 1}
    if (is.na(survival_stat[,5]) == TRUE){
                  survival_stat[,5] <- 1}
    print(paste("Subset #", r,":","(p = ", round(survival_stat[,5],3), ", HR = ",round(survival_stat[,2],3),", CI[",round(CI[,3],3),",",round(CI[,4],3),"])", sep=""))
    if (survival_stat[,5] <= 0.05){
      
      pdf(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"), r," ", fold.change$stim_condition[1], " ", fold.change$phospho[1],".pdf",sep =""),width = 10, height = 8)
      survival_plot <- ggsurvplot(model1, data=survival_data1, title = paste("Subset #", r," ", fold.change$stim_condition[1], " ", fold.change$phospho[1]," :", " (p = ", round(survival_stat[,5],3), ", HR = ",round(survival_stat[,2],3),", CI[",round(CI[,3],3),",",round(CI[,4],3),"])", sep=""),conf.int=F, pval=F, risk.table=T, tables.y.text = FALSE, legend.labs = c("Low", "High"), legend.title = "Group",censor.shape=124)
      print(survival_plot)
      dev.off()
      
      
    }}
  
  }}
```
