---
title: "Data Analysis Workflow Using Fold Change RAPID Todd's Data"
author: "Sierra Barone"
date: "10/09/2020"
output: pdf_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(flowCore)
library(Biobase)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(plyr)

# set working directory 
setwd(paste(getwd(),"/data_files/all_stim_dataset/", sep = ""))

# read in FCS files
fcs.files <- dir(pattern = "*.fcs")
data.lists <- lapply(fcs.files, read.FCS)

# read in csv file
csv.file <- dir(pattern = "*.csv")
fold.change.data = read.csv(csv.file[1])

# rename levels for stim condition and phospho
levels(fold.change.data$stim_condition)<-c("H2O2","IFNa","IL2","IL6")
fold.change.data[which(fold.change.data$stim_condition=="IL-2"),2]<-"IL2"
fold.change.data[which(fold.change.data$stim_condition=="IL-6"),2]<-"IL6"
levels(fold.change.data$phospho)<-c(unique(fold.change.data$phospho))

```

```{r make_plots}

# create plots and export
dir.create(file.path(getwd(), "output files"), showWarnings = FALSE)

for (i in 1:length(data.lists)){
patient = str_split(data.lists[[i]]@description[["FILENAME"]]," ")[[1]][2]
condition = str_split(str_split(data.lists[[i]]@description[["FILENAME"]]," ")[[1]][3],"_")[[1]][1]
data.to.plot = as.data.frame(data.lists[[i]]@exprs)[,c(65:67)]
colnames(data.to.plot)[3]<-"FlowSOM_cluster_ID"

for (z in 1:length(levels(fold.change.data$phospho))){
  fold.change <- fold.change.data %>%
    dplyr::filter(`stim_condition` == condition, `patient_ID` == patient,`phospho`== levels(fold.change.data$phospho)[z])

  plot.features <- merge(data.to.plot,fold.change, by  = "FlowSOM_cluster_ID") 
  tsne.data = cbind(plot.features$tSNE1,plot.features$tSNE2)
  range <- apply(apply(tsne.data, 2, range), 2, diff)
  graphical.ratio <- (range[1]/range[2])
  
pdf(paste("./output files/",strftime(Sys.time(),"%Y-%m-%d_%H%M%S"),"Patient:",patient," Condition:",condition," Readout:",levels(fold.change$phospho)[z],".pdf",sep =""))
   print(ggplot(data.frame(x = plot.features$tSNE1, 
                    y = plot.features$tSNE2, 
                    col = plot.features$fold_change)) + coord_fixed(ratio=graphical.ratio) + 
    geom_point(aes(x=x, y=y, color=col),cex = 1.5) + 
    labs(x = "t-SNE 1", y = "t-SNE 2", 
         color = "Fold Change", title = paste0("Patient:",patient," Condition:",condition," Readout:",levels(fold.change$phospho)[z])) + theme_bw() + scale_color_gradientn(colors = c("#A8C3F4", "#17499B", "gray40", "yellow", "#FAF7C9"),limits = c(-2.26,2.26)))
  dev.off()}
}
```
